/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.AddressController;
const Errors = testerlib.Errors;
const GroupConfirmFile44Enum = testerlib.GroupConfirmFile44Enum;
const AudioUrl43Enum = testerlib.AudioUrl43Enum;
const Status24Enum = testerlib.Status24Enum;
const Fileformat37Enum = testerlib.Fileformat37Enum;
const Type36Enum = testerlib.Type36Enum;
const AudioFormatEnum = testerlib.AudioFormatEnum;
const InterruptedCallStatusEnum = testerlib.InterruptedCallStatusEnum;
const IfMachine32Enum = testerlib.IfMachine32Enum;
const HttpActionEnum = testerlib.HttpActionEnum;
const AudioDirection29Enum = testerlib.AudioDirection29Enum;
const SendEmailAsEnum = testerlib.SendEmailAsEnum;
const TemplateData = testerlib.TemplateData;
const GroupConfirmFileEnum = testerlib.GroupConfirmFileEnum;
const AudioUrlEnum = testerlib.AudioUrlEnum;
const StatusEnum = testerlib.StatusEnum;
const FileformatEnum = testerlib.FileformatEnum;
const IfMachineEnum = testerlib.IfMachineEnum;
const TypeEnum = testerlib.TypeEnum;
const NumbertypeEnum = testerlib.NumbertypeEnum;
const DirectionEnum = testerlib.DirectionEnum;
const Direction4Enum = testerlib.Direction4Enum;
const AudioDirectionEnum = testerlib.AudioDirectionEnum;
const PlayDtmfDirectionEnum = testerlib.PlayDtmfDirectionEnum;
const MergeNumberEnum = testerlib.MergeNumberEnum;
const MActivateEnum = testerlib.MActivateEnum;
const ProductCodeEnum = testerlib.ProductCodeEnum;
const Status12Enum = testerlib.Status12Enum;
const NumberType14Enum = testerlib.NumberType14Enum;
const NumberType15Enum = testerlib.NumberType15Enum;
const MError = testerlib.MError;
const Message = testerlib.Message;
const Direction23Enum = testerlib.Direction23Enum;
const NumberType24Enum = testerlib.NumberType24Enum;
const Status25Enum = testerlib.Status25Enum;
const ActivateStatusEnum = testerlib.ActivateStatusEnum;
const MergeNumberStatusEnum = testerlib.MergeNumberStatusEnum;
const ProductCode30Enum = testerlib.ProductCode30Enum;
const Numbertype16Enum = testerlib.Numbertype16Enum;
const PlayDtmfDirection38Enum = testerlib.PlayDtmfDirection38Enum;
const MergeNumber40Enum = testerlib.MergeNumber40Enum;
const ActivateEnum = testerlib.ActivateEnum;
const ProductCode27Enum = testerlib.ProductCode27Enum;


describe("AddressController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * List All Address 
     */
    it("should testTestListAddresses response", function testTestListAddressesTest(done) {
        // parameters for the API call
        let page = null;
        let pagesize = null;
        let addressid = null;
        let dateCreated = null;

        controller.createListAddresses(page, pagesize, addressid, dateCreated, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
