/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.ConferenceController;
const AudioUrlEnum = testerlib.AudioUrlEnum;

describe("ConferenceController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Retrieve a list of conference objects.
     */
    it("should testTestListConferences response", function testTestListConferencesTest(done) {
        // parameters for the API call
        let page = null;
        let pagesize = null;
        let friendlyName = null;
        let dateCreated = null;

        controller.createListConferences(page, pagesize, friendlyName, dateCreated, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
