/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.PhoneNumberController;
const NumbertypeEnum = testerlib.NumbertypeEnum;
const NumberType14Enum = testerlib.NumberType14Enum;
const NumberType15Enum = testerlib.NumberType15Enum;

describe("PhoneNumberController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Retrieve a list of purchased phones numbers associated with your Ytel account.
     */
    it("should testTestListNumbers response", function testTestListNumbersTest(done) {
        // parameters for the API call
        let page = null;
        let pageSize = null;
        let numberType = null;
        let friendlyName = null;

        controller.createListNumbers(page, pageSize, numberType, friendlyName, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
