/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.TranscriptionController;
const Status12Enum = testerlib.Status12Enum;

describe("TranscriptionController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Retrieve a list of transcription objects for your Ytel account.
     */
    it("should testTestListTranscriptions response", function testTestListTranscriptionsTest(done) {
        // parameters for the API call
        let page = null;
        let pagesize = null;
        let status = null;
        let dateTranscribed = null;

        controller.createListTranscriptions(page, pagesize, status, dateTranscribed, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
