/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.UsageController;
const ProductCodeEnum = testerlib.ProductCodeEnum;

describe("UsageController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Retrieve usage metrics regarding your Ytel account. The results includes inbound/outbound voice calls and inbound/outbound SMS messages as well as carrier lookup requests.
     */
    it("should testTestListUsage response", function testTestListUsageTest(done) {
        // parameters for the API call
        let productCode = null;
        let startDate = null;
        let endDate = null;
        let includeSubAccounts = null;

        controller.createListUsage(productCode, startDate, endDate, includeSubAccounts, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
