/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ActivateEnum = {

    /**
     * TODO: Write general description for this element
     */
    M_ACTIVATE: 1,

    /**
     * TODO: Write general description for this element
     */
    DE_ACTIVATE: 0,

};

module.exports = ActivateEnum;
