/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const AudioDirectionEnum = {

    /**
     * TODO: Write general description for this element
     */
    MIN: 'in',

    /**
     * TODO: Write general description for this element
     */
    OUT: 'out',

};

module.exports = AudioDirectionEnum;
