/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AudioUrl43Enum = {

    /**
     * mp3 file
     */
    MP_3: 'mp3',

    /**
     * wav file
     */
    WAV: 'wav',

};

module.exports = AudioUrl43Enum;
