/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Direction23Enum = {

    /**
     * in direction
     */
    MIN: 'in',

    /**
     * out direction
     */
    OUT: 'out',

    /**
     * both
     */
    BOTH: 'both',

};

module.exports = Direction23Enum;
