/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const IfMachine32Enum = {

    /**
     * TODO: Write general description for this element
     */
    MCONTINUE: 'continue',

    /**
     * TODO: Write general description for this element
     */
    HANGUP: 'hangup',

};

module.exports = IfMachine32Enum;
