/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const InterruptedCallStatusEnum = {

    /**
     * Interrupt Call will be cancel
     */
    CANCELED: 'canceled',

    /**
     * Interrupt Call is complete
     */
    COMPLETED: 'completed',

};

module.exports = InterruptedCallStatusEnum;
