/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const MActivateEnum = {

    /**
     * TODO: Write general description for this element
     */
    ACTIVATE: 1,

    /**
     * TODO: Write general description for this element
     */
    DE_ACTIVATE: 0,

};

module.exports = MActivateEnum;
