/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const MergeNumberEnum = {

    /**
     * TODO: Write general description for this element
     */
    MDELETE: 0,

    /**
     * TODO: Write general description for this element
     */
    MERGE: 1,

};

module.exports = MergeNumberEnum;
