/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const NumbertypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    ALL: 'all',

    /**
     * TODO: Write general description for this element
     */
    VOICE: 'voice',

    /**
     * TODO: Write general description for this element
     */
    SMS: 'sms',

};

module.exports = NumbertypeEnum;
