/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const NumberType24Enum = {

    /**
     * Get all phone Number type
     */
    ALL: 'all',

    /**
     * Get only voice number type
     */
    VOICE: 'voice',

    /**
     * Get Only SMs number type
     */
    SMS: 'sms',

};

module.exports = NumberType24Enum;
