/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ProductCode27Enum = {

    /**
     * TODO: Write general description for this element
     */
    ALL: 0,

    /**
     * TODO: Write general description for this element
     */
    ENUM_1: 1,

    /**
     * TODO: Write general description for this element
     */
    ENUM_2: 2,

    /**
     * TODO: Write general description for this element
     */
    ENUM_3: 3,

    /**
     * TODO: Write general description for this element
     */
    ENUM_4: 4,

    /**
     * TODO: Write general description for this element
     */
    TRANSCRIPTION: 5,

    /**
     * TODO: Write general description for this element
     */
    EMAIL: 6,

    /**
     * TODO: Write general description for this element
     */
    CONFERENCE: 7,

    /**
     * TODO: Write general description for this element
     */
    CARRIER: 8,

    /**
     * TODO: Write general description for this element
     */
    ENUM_9: 9,

    /**
     * TODO: Write general description for this element
     */
    ENUM_10: 10,

    /**
     * TODO: Write general description for this element
     */
    ENUM_11: 11,

    /**
     * TODO: Write general description for this element
     */
    ENUM_12: 12,

    /**
     * TODO: Write general description for this element
     */
    ENUM_13: 13,

};

module.exports = ProductCode27Enum;
