/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Status25Enum = {

    /**
     * TODO: Write general description for this element
     */
    INPROGRESS: 'inprogress',

    /**
     * TODO: Write general description for this element
     */
    SUCCESS: 'success',

    /**
     * TODO: Write general description for this element
     */
    FAILURE: 'failure',

};

module.exports = Status25Enum;
