/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Type36Enum = {

    /**
     * Email send as text format
     */
    TEXT: 'text',

    /**
     * Email send as HTML format
     */
    HTML: 'html',

};

module.exports = Type36Enum;
