/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TypeEnum = {

    /**
     * Email send as text format
     */
    TEXT: 'text',

    /**
     * Email send as HTML format
     */
    HTML: 'html',

};

module.exports = TypeEnum;
