/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Errors = require('../lib/Models/Errors');
const TemplateData = require('../lib/Models/TemplateData');
const MError = require('../lib/Models/MError');
const Message = require('../lib/Models/Message');

const classMap = {
    Errors,
    TemplateData,
    MError,
    Message,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
