/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const _request = require('../Http/Client/RequestClient');
const _configuration = require('../configuration');
const _apiHelper = require('../APIHelper');
const _baseController = require('./BaseController');

class ConferenceController {
    /**
     * Play an audio file during a conference.
     *
     * @param  {array}  input    Array with all options for search
     * @param {string} input['conferenceSid'] The unique identifier for a conference object.
     * @param {string} input['participantSid'] The unique identifier for a participant object.
     * @param {AudioUrlEnum} input['audioUrl'] The URL for the audio file that is to be played
     * during the conference. Multiple audio files can be
     * chained by using a semicolon.
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesPlayAudio(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        const _queryBuilder = `${_baseUri}${'/conferences/playAudio.json'}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            ConferenceSid: input.conferenceSid,
            ParticipantSid: input.participantSid,
            AudioUrl: (input.audioUrl !== null) ? input.audioUrl : null,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Remove a participant from a conference.
     *
     * @param  {array}  input    Array with all options for search
     * @param {string} input['conferenceSid'] The unique identifier for a conference object.
     * @param {string} input['participantSid'] The unique identifier for a participant object.
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesHangupParticipant(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        let _queryBuilder = `${_baseUri}${'/conferences/hangupParticipant.json'}`;

        // process query parameters
        _queryBuilder = _apiHelper.appendUrlWithQueryParameters(_queryBuilder, {
            ParticipantSid: input.participantSid,
        });

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            ConferenceSid: input.conferenceSid,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Retrieve information about a conference by its ConferenceSid.
     *
     * @param {string} conferenceSid The unique identifier of each conference resource
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesViewconference(conferenceSid, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        const _queryBuilder = `${_baseUri}${'/conferences/viewconference.json'}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            ConferenceSid: conferenceSid,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Retrieve a list of conference objects.
     *
     * @param  {array}  input    Array with all options for search
     * @param {int} input['page'] (optional) The page count to retrieve from the total results in
     * the collection. Page indexing starts at 1.
     * @param {int} input['pagesize'] (optional) Number of individual resources listed in the
     * response per page
     * @param {string} input['friendlyName'] (optional) Only return conferences with the specified
     * FriendlyName
     * @param {string} input['dateCreated'] (optional) Conference created date
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesListconference(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        const _queryBuilder = `${_baseUri}${'/conferences/listconference.json'}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            page: (input.page !== null) ? input.page : 1,
            pagesize: (input.pagesize !== null) ? input.pagesize : 10,
            FriendlyName: input.friendlyName,
            DateCreated: input.dateCreated,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Retrieve a list of participants for an in-progress conference.
     *
     * @param  {array}  input    Array with all options for search
     * @param {string} input['conferenceSid'] The unique identifier for a conference.
     * @param {int} input['page'] (optional) The page count to retrieve from the total results in
     * the collection. Page indexing starts at 1.
     * @param {int} input['pagesize'] (optional) The count of objects to return per page.
     * @param {bool} input['muted'] (optional) Specifies if participant should be muted.
     * @param {bool} input['deaf'] (optional) Specifies if the participant should hear audio in the
     * conference.
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesListParticipant(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        const _queryBuilder = `${_baseUri}${'/conferences/listParticipant.json'}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            ConferenceSid: input.conferenceSid,
            Page: (input.page !== null) ? input.page : 1,
            Pagesize: (input.pagesize !== null) ? input.pagesize : 10,
            Muted: input.muted,
            Deaf: input.deaf,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Retrieve information about a participant by its ParticipantSid.
     *
     * @param  {array}  input    Array with all options for search
     * @param {string} input['conferenceSid'] The unique identifier for a conference object.
     * @param {string} input['participantSid'] The unique identifier for a participant object.
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesViewParticipant(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        const _queryBuilder = `${_baseUri}${'/conferences/viewParticipant.json'}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            ConferenceSid: input.conferenceSid,
            ParticipantSid: input.participantSid,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Add Participant in conference
     *
     * @param  {array}  input    Array with all options for search
     * @param {string} input['conferenceSid'] The unique identifier for a conference object.
     * @param {string} input['participantNumber'] The phone number of the participant to be added.
     * @param {bool} input['muted'] (optional) Specifies if participant should be muted.
     * @param {bool} input['deaf'] (optional) Specifies if the participant should hear audio in the
     * conference.
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesAddParticipant(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        const _queryBuilder = `${_baseUri}${'/conferences/addParticipant.json'}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            ConferenceSid: input.conferenceSid,
            ParticipantNumber: input.participantNumber,
            Muted: input.muted,
            Deaf: input.deaf,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Here you can experiment with initiating a conference call through Ytel and view the
     * request response generated when doing so.
     *
     * @param  {array}  input    Array with all options for search
     * @param {string} input['from'] A valid 10-digit number (E.164 format) that will be initiating
     * the conference call.
     * @param {string} input['to'] A valid 10-digit number (E.164 format) that is to receive the
     * conference call.
     * @param {string} input['url'] URL requested once the conference connects
     * @param {string} input['method'] (optional) Specifies the HTTP method used to request the
     * required URL once call connects.
     * @param {string} input['statusCallBackUrl'] (optional) URL that can be requested to receive
     * notification when call has ended. A set of
     * default parameters will be sent here once the
     * conference is finished.
     * @param {string} input['statusCallBackMethod'] (optional) Specifies the HTTP methodlinkclass
     * used to request StatusCallbackUrl.
     * @param {string} input['fallbackUrl'] (optional) URL requested if the initial Url parameter
     * fails or encounters an error
     * @param {string} input['fallbackMethod'] (optional) Specifies the HTTP method used to request
     * the required FallbackUrl once call connects.
     * @param {bool} input['record'] (optional) Specifies if the conference should be recorded.
     * @param {string} input['recordCallBackUrl'] (optional) Recording parameters will be sent here
     * upon completion.
     * @param {string} input['recordCallBackMethod'] (optional) Specifies the HTTP method used to
     * request the required URL once conference
     * connects.
     * @param {string} input['scheduleTime'] (optional) Schedule conference in future. Schedule
     * time must be greater than current time
     * @param {int} input['timeout'] (optional) The number of seconds the call stays on the line
     * while waiting for an answer. The max time limit is 999 and the
     * default limit is 60 seconds but lower times can be set.
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesCreateConference(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        let _queryBuilder = `${_baseUri}${'/conferences/createConference.json'}`;

        // process query parameters
        _queryBuilder = _apiHelper.appendUrlWithQueryParameters(_queryBuilder, {
            Url: input.url,
        });

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            From: input.from,
            To: input.to,
            Method: (input.method !== null) ? input.method : 'POST',
            StatusCallBackUrl: input.statusCallBackUrl,
            StatusCallBackMethod: input.statusCallBackMethod,
            FallbackUrl: input.fallbackUrl,
            FallbackMethod: input.fallbackMethod,
            Record: input.record,
            RecordCallBackUrl: input.recordCallBackUrl,
            RecordCallBackMethod: input.recordCallBackMethod,
            ScheduleTime: input.scheduleTime,
            Timeout: input.timeout,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * Deaf Mute Participant
     *
     * @param  {array}  input    Array with all options for search
     * @param {string} input['conferenceSid'] ID of the active conference
     * @param {string} input['participantSid'] ID of an active participant
     * @param {bool} input['muted'] (optional) Mute a participant
     * @param {bool} input['deaf'] (optional) Make it so a participant cant hear
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static createConferencesDeafMuteParticipant(input, callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        const _queryBuilder = `${_baseUri}${'/conferences/deafMuteParticipant.json'}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare form data
        const _form = {
            conferenceSid: input.conferenceSid,
            ParticipantSid: input.participantSid,
            Muted: input.muted,
            Deaf: input.deaf,
        };

        // remove null values
        _apiHelper.cleanObject(_form);

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'POST',
            form: _form,
            username: _configuration.basicAuthUserName,
            password: _configuration.basicAuthPassword,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, _response.body, _context);
                    _fulfill(_response.body);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
}
module.exports = ConferenceController;
